project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "mscids-notes"
  google-analytics: "G-NZ8462CXQ1"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Applied Machine Learning and Predictive Modelling 1"
        href: fs26/mpm1/mpm1_notes.qmd
      - text: "Data Collection, Integration and Preprocessing"
        href: fs26/cip/cip_notes.qmd
      - text: "Data Quality"
        href: fs26/dq/dq_notes.qmd
      # - text: "Python for Data Science"
      #   menu:
      #     - text: "Notes"
      #       href: hs25/pds/pds_notes.qmd
      #     - text: "Exercises"
      #       href: hs25/pds/pds_exercises.qmd
      #     - text: "Mock Exam Solution"
      #       href: hs25/pds/pds_mock_exam.qmd
      #     - text: "Modul Exam FS2023"
      #       href: hs25/pds/pds_modul_exam_fs23.qmd
      # - text: "Classical and Bayesian Statistics"
      #   menu:
      #     - text: "Notes"
      #       href: hs25/sa/sa_notes.qmd
      #     - text: "Exercises"
      #       href: hs25/sa/sa_exercises.qmd
      # - text: "Linear Algebra 01"
      #   href: hs25/lia1/lia1_notes.qmd
      # - text: "Design of Experiments"
      #   menu:
      #     - text: "Notes"
      #       href: hs25/doe/doe_notes.qmd
      #     - text: "Exercises"
      #       href: hs25/doe/doe_exercises.qmd
      #     - text: "Exam Summary"
      #       href: hs25/doe/doe_exam_summary.qmd
      # - text: "Computer Science Concepts for Data Scientists"
      #   menu:
      #    - text: "Notes"
      #      href: hs25/csc/csc_notes.qmd
      #    - text: "Exercises"
      #      href: hs25/csc/csc_exercises.qmd
      # - text: "R-Bootcamp"
      #   href: hs25/r_bootcamp/r_bootcamp_notes.qmd
      - text: "How to"
        menu:
          - text: "Terminal"
            href: "howTo/terminal.qmd"
          - text: "Git/GitHub"
            href: "howTo/git.qmd"
          - text: "Python"
            href: "howTo/python.qmd"
          - text: "Python Packages"
            href: "howTo/pythonPackages.qmd"
          - text: "Python Project"
            href: "howTo/pythonProject.qmd"
      - text: "Resources"
        href: resources.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pdf: default